<?php get_template_part('header'); ?>
<?php get_template_part('elements/banner'); ?>
<?php get_template_part('elements/professional-services'); ?>
<?php get_template_part('elements/heavy-lifting'); ?>
<?php get_template_part('elements/latest-projects'); ?>
<?php get_template_part('elements/culture-values'); ?>
<?php get_template_part('elements/clients'); ?>
<?php get_template_part('elements/contact'); ?>
<?php get_template_part('elements/client-logos'); ?>
<?php get_template_part('elements/footer-widgets'); ?>
<?php get_template_part('footer'); ?>